---
- hosts: all
  become: yes
  tasks: 
  - name: install tree
    apt:
     name: tree   
     state: present
     tags: kds
    
  - name: install git
    apt:
      name: git
      state: present
      tags: kds

  - name: install wget
    apt:
     name: wget
     state: present
     tags: hari