---
- hosts: 172.31.21.35
  become: yes
  tasks: 
  - name: install git
    apt: 
      name: git
  - action: skip

  - name: install wget
    apt: 
      name: wget
    igore_errors: yes

  - name: install tree
    apt:
      name: tree