---
- hosts: webservers
  become: yes
  tasks:
  - name: install webservers on redhat
    yum:
      name: httpd
      state: present
    notify: restartwebserver
    when: ansible_os_family =="RedHat"