---
- hosts: webservers
  become: yes
  tasks:
  - name: install webservers on redhat
    yum:
      name: httpd
      state: present
    notify: restartwebserver
    when: ansible_os_family =="RedHat"

  - name: index.j2 to webservers
    template:
      src: index.j2
      dest: /var/www/html/index.j2
    notify: restartwebserver
    when: ansible_os_family =="RedHat"
  handlers:  
  - name: restartwebserver
    service:  
      name: httpd
      state: restarted