---
- hosts: all
  become:
  tasks:
  - name: this is git
    apt:
      name: git
      state: present
  - name: this is wget
    apt:
      name: wget
      state: present
  - name: this is apache2
    apt: 
       name: apache2
       state: present
  - name: start webserver
    service:
        name: apache2
        state: started
        enabled: yes
